
import Head from "next/head";
import Header from "@/components/Header"

export default function AboutPage() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <h1>Chi siamo:</h1>
      <p>Un negozio finto nato dall'esigenza di esercitarsi con l'hook useRoute di next</p>
    </>
  );
}
