import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import axios from "axios";

import Head from "next/head";
import Header from "@/components/Header"

import Card from "@/components/Card"

export default function ProductsPage() {
  const apiUrl = "https://fakestoreapi.com";
  const productsEndpoint = "products"

  const [product, setProduct] = useState([])

  const router = useRouter()

  const { id } = router.query

  if(!router.isReady) {
    return <div>Loading...</div>
  }

  function getProducts() {
    axios.get(`${apiUrl}/${productsEndpoint}/${id}`).then((r) => {
      console.log("Prodotti", r.data);

      setProduct(r.data)
    }).catch((e) => {
      console.log("Errore", e.message);
    })
  }

  useEffect(() => {
    getProducts()
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Card product={product} showDetails={true}/>
    </>
  );
}
