import { useEffect, useState } from "react";
import axios from "axios";

import Head from "next/head";
import Header from "@/components/Header"
import ProductList from "@/components/ProductList"

export default function ProductsPage() {
  const apiUrl = "https://fakestoreapi.com";
  const productsEndpoint = "products"

  const [products, setProducts] = useState([])

  function getProducts() {
    axios.get(`${apiUrl}/${productsEndpoint}`).then((r) => {
      console.log("Prodotti", r.data);

      setProducts(r.data)
    }).catch((e) => {
      console.log("Errore", e.message);
    })
  }

  useEffect(() => {
    getProducts()
  }, [])



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <ProductList products={products} />
    </>
  );
}
